# Generated by Django 3.2.5 on 2021-07-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('mensaje', models.CharField(max_length=250, verbose_name='Mensaje')),
            ],
        ),
    ]
